export const REGISTER_REQUEST='GET_MUSIC_RECORD_REQUEST';
export const REGISTER_SUCCESS='GET_MUSIC_RECORD_SUCCESS';
export const REGISTER_FAILURE='GET_MUSIC_RECORD_FAILURE';

export const LOGIN_REQUEST='GET_MUSIC_RECORD_REQUEST';
export const LOGIN_SUCCESS='GET_MUSIC_RECORD_SUCCESS';
export const LOGIN_FAILURE='GET_MUSIC_RECORD_FAILURE';

